### ISSUE TITLE
resource axis and time axis repeated css 

### ISSUE THREAD

**Issue by umarmohammed** [ngx-d3timeline/ngx-d3timeline#501]
```scss
.resources-axis .axis-group {
    &.Vertical {
      text-anchor: end;
      dominant-baseline: central;
    }
    &.Horizontal {
      text-anchor: middle;
    }
  }
  .time-axis .axis-group {
    &.Vertical {
      text-anchor: end;
      dominant-baseline: central;
    }
    &.Horizontal {
      text-anchor: middle;
    }
  }
```
